[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "The Digital Wiki"
authors = [{name = "Matthew Blackwood", email = "noreply@gmail.com"}]
dynamic = ["version", "description"]
